<a href="https://colab.research.google.com/github/prabhleenkaursaini/UCS420/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment-6 NumPy-II

Q1. Consider the following sensor readings:

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])


A sensor has an average measurement error of +2°C.



Perform the following without using a for loop:


a. Add 2°C to every reading using vectorization.


In [ ]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
corrected_temperature = temperature+2
print("Original temperature:", temperature)
print("Temperature after adding 2°C:", corrected_temperature)

Original temperature: [25 28 31 35 38 27 33 40]
Temperature after adding 2°C: [27 30 33 37 40 29 35 42]


b. Convert all temperatures from Celsius to Fahrenheit using: F = 9/5 C + 32


In [ ]:
fahrenheit = 9/5*corrected_temperature+32
print("Temperature in Fahrenheit:", fahrenheit)

Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


c. Identify all readings greater than 32°C using Boolean indexing.


In [ ]:
readings=temperature[temperature>32]
print("Readings greater than 32°C:", readings)

Readings greater than 32°C: [35 38 33 40]


d. Count how many readings exceed 32°C.


In [ ]:
count = np.sum(temperature>32)
print("Number of readings greater than 32°C:", count)

Number of readings greater than 32°C: 4


e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.


In [ ]:
print("Vectorization performs operations on the complete array at once,")
print("while Boolean indexing selects required values directly without a for loop.")

Vectorization performs operations on the complete array at once,
while Boolean indexing selects required values directly without a for loop.


Q2. The following matrix represents the number of daily steps recorded by four users over three days:


steps = np.array([


[5000, 6200, 7100],


[8000, 7500, 9000],


[4500, 5100, 4800],


[9000, 8500, 9500]])


Perform the following:


a. Calculate the total steps recorded.


In [ ]:
steps = np.array([[5000, 6200, 7100],[8000, 7500, 9000],[4500, 5100, 4800],[9000, 8500, 9500]])
total_steps = np.sum(steps)
print("Total steps:", total_steps)

Total steps: 84200


b. Calculate the mean number of steps.


In [ ]:
mean_steps = np.mean(steps)
print("Mean number of steps:", mean_steps)

Mean number of steps: 7016.666666666667


c. Find the maximum and minimum values.


In [ ]:
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

Maximum steps: 9500
Minimum steps: 4500


d. Calculate the total steps for each day using axis=0.


In [ ]:
day_total = np.sum(steps, axis=0)
print("Total steps for each day:", day_total)

Total steps for each day: [26500 27300 30400]


e. Calculate the total steps for each user using axis=1.


In [ ]:
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

Total steps for each user: [18300 24500 14400 27000]


f. Find the user/day position containing the maximum number of steps using argmax().


In [ ]:
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("User/day position:", max_position)
print("Maximum steps:", steps[max_position])

User/day position: (np.int64(3), np.int64(2))
Maximum steps: 9500


Q3. Write a Python program using NumPy to perform the following operations:


a. Create the following NumPy array:


original = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
original = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", original)

Original array: [1 2 3 4 5 6]


b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.


In [ ]:
subset = original[1:5]
print("Subset:", subset)

Subset: [2 3 4 5]


c. Modify the first element of subset to 999 and display both original and subset.


In [ ]:
subset[0] = 999
print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array.


In [ ]:
copied_array = original[1:5].copy()
copied_array[0] = 500
print("Original:", original)
print("Copied array:", copied_array)

Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.


In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print("3 x 4 matrix:")
print(matrix)

3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:


• First row

In [ ]:
print("First row:", matrix[0, :])

First row: [1 2 3 4]


• Last row


In [ ]:
print("Last row:", matrix[-1, :])

Last row: [ 9 10 11 12]


• Second column


In [ ]:
print("Second column:", matrix[:, 1])

Second column: [ 2  6 10]


• Elements from rows 1–2 and columns 2–3


In [ ]:
print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]


g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().


In [ ]:
flattened_array = matrix.flatten()
ravel_array = matrix.ravel()
print("Using flatten():", flattened_array)
print("Using ravel():", ravel_array)

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


h. Modify an element in the array returned by ravel() and observe whether the original array is affected.


In [ ]:
ravel_array[0] = 100
print("Original matrix after modifying ravel():")
print(matrix)
print("Ravel array:", ravel_array)

Original matrix after modifying ravel():
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel array: [100   2   3   4   5   6   7   8   9  10  11  12]


i. Modify an element in the array returned by flatten() and observe whether the original array is affected.


In [ ]:
flattened_array[1] = 200
print("Original matrix after modifying flatten():")
print(matrix)
print("Flattened array:", flattened_array)

Original matrix after modifying flatten():
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array: [  1 200   3   4   5   6   7   8   9  10  11  12]


j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.


In [ ]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors:


• Sleep hours


• Activity level


• Stress level


Consider:


X = np.array([


[6, 70, 3],


[5, 50, 6],


[8, 80, 2],


[4, 30, 8]


])


y = np.array([40, 65, 30, 85])


Here, each row represents one user and each column represents a feature.


Perform the following:


a. Display the shape and dimensions of X.


In [ ]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)


Shape of X: (4, 3)
Dimensions of X: 2


b. Calculate: X.T and explain what the transpose represents.


In [ ]:
print("X transpose:")
print(X.T)
print("The transpose changes rows into columns and columns into rows.")

X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
The transpose changes rows into columns and columns into rows.


c. Calculate the matrix product: X.T @ X


In [ ]:
XTX = X.T @ X
print("X.T @ X:")
print(XTX)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.


In [ ]:
XTX_inverse = np.linalg.inv(XTX)
print("Inverse of X.T @ X:")
print(XTX_inverse)

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


e. Implement the Ordinary Least Squares equation: β = (X.T X)^-1 X.T y using NumPy.


In [ ]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Beta coefficients:", beta)

Beta coefficients: [-0.15921454  0.14083853 10.06302242]


f. Explain what the resulting coefficients represent in the context of the three user features.


In [ ]:
print("The coefficients show how the predicted assistance score changes")
print("with sleep hours, activity level, and stress level.")

The coefficients show how the predicted assistance score changes
with sleep hours, activity level, and stress level.


g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.


In [ ]:
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score:", predicted_score)

Predicted assistance score: 75.27862544779117
