<a href="https://colab.research.google.com/github/prabhleenkaursaini/UCS420/blob/main/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment-5 NumPy Introduction-1

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:


a) Addition of 2 in all the element


In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
result = a + 2
print("Original array:", a)
print("After adding 2:", result)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]


b) Multiply 3 with all the elements


In [3]:
result = a*3
print("Original array:", a)
print("After multiplying by 3:", result)

Original array: [10 20 30 40 50]
After multiplying by 3: [ 30  60  90 120 150]


c) Divide every element by 2


In [4]:
result = a/2
print("Original array:", a)
print("After dividing by 2:", result)

Original array: [10 20 30 40 50]
After dividing by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:


a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:


i. x = np.array([1,2,3,4,5,1,2,1,1,1])


In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
max_count = counts.max()
for value in values[counts == max_count]:
    print("Most frequent value:", value)
    print("Frequency:", max_count)
    print("Indices:", np.where(x == value)[0])

Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
max_count = counts.max()
for value in values[counts == max_count]:
    print("Most frequent value:", value)
    print("Frequency:", max_count)
    print("Indices:", np.where(y == value)[0])

Most frequent value: 1
Frequency: 3
Indices: [0 1 2]
Most frequent value: 3
Frequency: 3
Indices: [4 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:


In [8]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


a) Access 1st row, 2nd column


In [9]:
print(arr[0, 1])

20


b) Access 3rd row, 1st column


In [10]:
print(arr[2, 0])

70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?


In [13]:
prabhleen = np.linspace(10, 100, 25)
print("Array:", prabhleen)
print("Dimensions:", prabhleen.ndim)
print("Shape:", prabhleen.shape)
print("Total elements:", prabhleen.size)
print("Data type:", prabhleen.dtype)
print("Total bytes:", prabhleen.nbytes)
transpose_array = prabhleen.reshape(1, 25)
print("Transpose using reshape():")
print(transpose_array)
print("Transpose using T:")
print(prabhleen.T)
print("Yes, T can be used, but for a 1-D array it does not change the shape.")

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Yes, T can be used, but for a 1-D array it does not change the shape.


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.


In [14]:
ucs420_prabhleen = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
print("Array:")
print(ucs420_prabhleen)
print("Mean:", np.mean(ucs420_prabhleen))
print("Median:", np.median(ucs420_prabhleen))
print("Maximum:", np.max(ucs420_prabhleen))
print("Minimum:", np.min(ucs420_prabhleen))
print("Unique elements:", np.unique(ucs420_prabhleen))
reshaped_ucs420_prabhleen = ucs420_prabhleen.reshape(4, 3)
print("Reshaped array:")
print(reshaped_ucs420_prabhleen)
resized_ucs420_prabhleen = np.resize(ucs420_prabhleen, (2, 3))
print("Resized array:")
print(resized_ucs420_prabhleen)


Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
